Pull in code from weibeld/heroku-buildpack-run

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -29,3 +29,61 @@ EOM
 fi
 
 $heroku_buildpack_ruby_dir/bin/ruby $BIN_DIR/support/ruby_compile $@
+
+
+# Indentation
+indent()     { sed 's/^/       /'; }
+arrow()      { sed 's/^/-----> /'; }
+indent-err() { sed "s/^/$(printf '\033')[31m       /;s/$/$(printf '\033')[0m/"; }
+arrow-err()  { sed "s/^/$(printf '\033')[31m-----> /;s/$/$(printf '\033')[0m/"; }
+
+cd "$BUILD_DIR"
+
+# If BUILDPACK_RUN_LOAD_CONFIG is set, create env vars for all of the app's
+# config vars (except thos specified in BUILDPACK_RUN_LOAD_CONFIG_SKIP). The
+# env vars are not created immediately, but the commands to create them are
+# written to a file, which is then sourced before the user-supplied commands
+# are executed (this is to prevent name clashes between the config vars and
+# env vars used by this script).
+BUILDPACK_RUN_CONFIG_FILE=$(mktemp)
+if [[ -f "$ENV_DIR/BUILDPACK_RUN_LOAD_CONFIG" ]]; then
+  echo "Loading config vars into environment" | arrow
+  skip='^()$'
+  if [[ -f "$ENV_DIR/BUILDPACK_RUN_LOAD_CONFIG_SKIP" ]]; then
+    skip="^($(tr ':' '|' <"$ENV_DIR/BUILDPACK_RUN_LOAD_CONFIG_SKIP"))$"
+    echo "(except: $(cat "$ENV_DIR/BUILDPACK_RUN_LOAD_CONFIG_SKIP"))" | indent
+  fi
+  shopt -s nullglob
+  for f in "$ENV_DIR"/*; do
+    if ! grep -qE "$skip" <<<$(basename "$f"); then
+      echo "export $(basename "$f")=\$(cat "$f")" >>"$BUILDPACK_RUN_CONFIG_FILE"
+    fi
+  done
+fi
+
+# Extract commands from BUILDPACK_RUN config var
+if [[ -f "$ENV_DIR/BUILDPACK_RUN" ]]; then
+  BUILDPACK_RUN_COMMANDS=$(cat "$ENV_DIR/BUILDPACK_RUN")
+elif [[ -f buildpack-run.sh ]]; then
+  BUILDPACK_RUN_COMMANDS=./buildpack-run.sh
+else
+  echo "Error: can't apply buildpack" | arrow-err
+  cat <<EOF | indent-err
+You must either create an executable script named buildpack-run.sh
+in the root directory of your app, or specify one or more commands
+to execute in the BUILDPACK_RUN config variable (colon-delimited).
+See https://github.com/weibeld/heroku-buildpack-run#usage
+EOF
+  exit 1
+fi
+IFS=':' BUILDPACK_RUN_COMMANDS=($BUILDPACK_RUN_COMMANDS)
+
+# Run commands
+for BUILDPACK_RUN_CMD in ${BUILDPACK_RUN_COMMANDS[@]}; do
+  echo "Running: $BUILDPACK_RUN_CMD" | arrow
+  . "$BUILDPACK_RUN_CONFIG_FILE"
+  eval "$BUILDPACK_RUN_CMD" || {
+    echo "Aborting: '$BUILDPACK_RUN_CMD' exited with exit code $?" | arrow-err
+    exit 1
+  }
+done
